### ISSUE TITLE
Deduplicate pg_packets_prepare_hash_keys in bricks

### ISSUE THREAD

**Issue by outscale-mgo** [outscale/packetgraph#31]
vtep call pg_packets_prepare_hash_keys.
switch call pg_packets_prepare_hash_keys.
antispoof can be faster if the packets was prepare by  pg_packets_prepare_hash_keys.

We should call pg_packets_prepare_hash_keys after the nic brick, of create a brick to call pg_packets_prepare_hash_keys and made an option to stop doing that in switch.
After that we can optimize the antispoof, and all other brick which check the ether_addr.

**Comment by outscale-jju** [comment]
done
