### ISSUE TITLE
Make all packet source have L2_len set

### ISSUE THREAD

**Issue by outscale-jju** [outscale/packetgraph#370]
We should use mbuf metadata to get L2 length and it should be set for all generated packets.
This includes pollable bricks (like nic, vhost, etc..) and bricks who may generate packets (like vtep which sends igpm subscriptions).
Once this metadata is correctly set, packets won't have to be inspected latter by other bricks (to check vlan for example).

**Comment by outscale-gle** [comment]
That seem to be resolved, it can be close.
