### ISSUE TITLE
core: some bricks should not be allowed nor able to forward to more than one brick

### ISSUE THREAD

**Issue by outscale-mgo** [outscale/packetgraph#38]
Today, we can classify our brick in 2 categories: the social brick which are dealing with lot of neighbors(hub, switch vtep) and the associable one(diode, firewall, nic, vhost...), which are not make to deal with more that 2 brick(one on each side) and actually if we try to link an associable brick with a lot of neighbor, I'm not really sure about what will happen, and this can cause bugs.

We need to forbid associable bricks to deal with more than 1 neighbor on each side, and so we will be able to optimize the forwarding of the associable bricks.

**Comment by outscale-jju** [comment]
old ticket, closing
